1.Write a python code to create a array in different ways

### creating a array

In [48]:
# From List
list1 = [1,2,3,4,5,5,4,3,5,7,8]

In [49]:
import numpy as num

In [52]:
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5, 5, 4, 3, 5, 7, 8])

In [53]:
type(arr)

numpy.ndarray

In [54]:
# From Tuple
tup = (1,2,25,36,5,3,4,6,7,89,45)


In [55]:
arr1 = np.array(tup)
arr1

array([ 1,  2, 25, 36,  5,  3,  4,  6,  7, 89, 45])

In [56]:
type(arr1)

numpy.ndarray

In [6]:
# direct array creation
arr2 = np.array([1,2,3,7,8,9,4,5,6,57,56])
arr2

array([ 1,  2,  3,  7,  8,  9,  4,  5,  6, 57, 56])

In [7]:
type(arr2)

numpy.ndarray

2. Array Creation:
    
    a. Create a 1D Numpy array containing the first  12 positive integers as arr1.
    
    b. Create a 1D Numpy array1 with 20 elements containing integers between 0 and 12 using linspace.

In [8]:
# a
arr1 = np.arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
# b 
array1 = np.linspace(0,12,20)
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

3 . Find all atrributes of array1 and array2

In [10]:
array1 = np.arange(1,13)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
array2 =  np.linspace(0,12,20)
array2

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

### Attributes of array1

In [12]:
array1.dtype

dtype('int32')

In [13]:
array1.ndim

1

In [14]:
array1.size

12

In [15]:
array1.nbytes

48

In [16]:
array1.itemsize

4

### Attributes of array2

In [17]:
array2.dtype

dtype('float64')

In [18]:
array2.ndim

1

In [19]:
array2.size

20

In [20]:
array2.nbytes

160

In [21]:
array2.itemsize

8

Apply measure and describe the data to above arrays usind Numpy.

### Measure of central tendancy of array1

In [22]:
# Mean
np.mean(array1)

6.5

In [29]:
#median
np.median(array1)

6.5

### Measure of spread of array1

In [23]:
# range 
range1 = np.max(array1)-np.min(array1)
range1

11

In [24]:
# varince
np.var(array1)

11.916666666666666

In [25]:
# std
np.std(array1)

3.452052529534663

##### IOR of array1

In [26]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
q3 = np.percentile(array1,75)
q3

9.25

In [28]:
q1 = np.percentile(array1,25)
q1

3.75

In [29]:
IQR = q3-q1
IQR

5.5

### to find outlier

In [30]:
lower_limit = q1-(1.5 * IQR)
lower_limit

-4.5

In [31]:
upper_limit = q3+(1.5*IQR)
upper_limit

17.5

In [32]:
array1>upper_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [33]:
array1<lower_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

- from above upper limit and lower limit both case are fail, hence there is no outlier

### Measure of central Tendancy of array2

In [34]:
array2

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

In [35]:
# mean
np.mean(array2)

5.999999999999999

In [36]:
# median
np.median(array2)

6.0

### Measure of spread

In [37]:
# range
range2 = np.max(array2)-np.min(array2)
range2

12.0

In [38]:
# varinace
np.var(array2)

13.26315789473684

In [39]:
# std
np.std(array2)

3.6418618720013036

##### IQR

In [40]:
q1 = np.percentile(array2,25)
q1

3.0

In [41]:
q3 = np.percentile(array2,75)
q3

9.0

In [42]:
# IQR
IQR = q3-q1
IQR

6.0

#### To find outlier of array2

In [43]:
array2

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

In [44]:
lower_limit = q1-(1.5*IQR)
lower_limit

-6.0

In [45]:
upper_limit = q3+(1.5*IQR)
upper_limit

18.0

In [46]:
array2>upper_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [47]:
array2<lower_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

- from above upper limit and lower limit both the  cases are failed, so there is no outlier